Добавляет разметку главной страницы и каталога
htmlacademy-htmlcss/2122221-gllacy-34 pull request #2
Opened 2022-05-25 14:53 UTC by annvolfers

2022-05-25 18:41 UTC, Dima-Dim requested changes

2022-05-25 18:41 UTC, Dima-Dim commented on index.html
> +      <h2 class="visually-hidden">Несколько видов мороженого</h2>
Тут не нужно придумывать скрытый заголовок, есть видимые, ну и в целом не особо много в нём смысла.

2022-05-25 18:41 UTC, Dima-Dim commented on index.html
> +      <ol class="slider-pagination">
С этим списком всё хорошо. А вот со списком самих слайдов нет. Нужно доразделить сущности из которых состоит слайдер.

2022-05-25 18:41 UTC, Dima-Dim commented on index.html
> +          <p class="about-description">Всё наше мороженое изготавливается на собственном производстве с использованием
`p` тут не обязателен.

2022-05-25 18:41 UTC, Dima-Dim commented on index.html
> +      <h2 class="blog-title">Новое в нашем блоге</h2>
Тут нет самого материала, по этому не понятно к чему заголовок. А заголовок сам по себе не особо имеет смысл.

2022-05-25 18:52 UTC, annvolfers commented on index.html
> +      <h2 class="visually-hidden">Несколько видов мороженого</h2>
Действительно, уберу

2022-05-25 18:53 UTC, annvolfers commented on index.html
> +      <ol class="slider-pagination">
Можно чуть подробнее? Списка слайдов то и нет пока, сделать? Или вы о другом?

2022-05-25 19:00 UTC, annvolfers commented on index.html
> +      <h2 class="blog-title">Новое в нашем блоге</h2>
В section какой-то заголовок ведь обязательно должен быть, h2 на p заменить, а h3 на h2 - правильно будет?

2022-05-25 19:03 UTC, Dima-Dim commented on index.html
> +      <ol class="slider-pagination">
Мока можно сделать хотя бы один, чтобы наметить структуру и показать логику.

2022-05-25 19:04 UTC, Dima-Dim commented on index.html
> +      <h2 class="blog-title">Новое в нашем блоге</h2>
Значит, возможно, это и не section.

2022-05-26 06:35 UTC, Dima-Dim commented on index.html
> +      <button class="button button-main" type="button">Заказать</button>
У каждого слайда своё Заказать.

2022-05-26 06:35 UTC, merged